export const projects = [
  {
    title: "Goal setter",
    description: "MERN app for setting goals.",
    image: "/images/1.png",
    tags: ["MongoDB", "Express", "React", "Node", "Redux"],
    source: "https://github.com/Leviantt/goal-setter/",
    visit: "https://levs-goal-setter.herokuapp.com/",
    id: 0,
  },
  {
    title: "Delicious",
    description:
      "A convenient application for finding recipes. Requests are made on the Spoonacular API.",
    image: "/images/2.png",
    tags: ["React", "Typescript", "React-router-dom"],
    source: "https://github.com/Leviantt/delicious/",
    visit: "https://leviantt.github.io/delicious/",
    id: 1,
  },
  {
    title: "Keep track",
    description: "An application for tracking projects.",
    image: "/images/3.png",
    tags: ["React", "Typescript", "Redux"],
    source: "https://github.com/Leviantt/keep-track/",
    visit: "https://phenomenal-cajeta-ba42a9.netlify.app/",
    id: 2,
  },
  {
    title: "File sharing",
    description: "File sharing application based on MongoDB Atlas.",
    image: "/images/4.png",
    tags: ["Node", "Express", "MongoDB", "Bcrypt"],
    source: "https://github.com/Leviantt/file-sharing-node/",
    visit: "https://levs-file-sharing-app.herokuapp.com/",
    id: 3,
  },
  {
    title: "Movie search",
    description:
      "A simple application for finding movies, with a focus on CSS. Requests are made on the omdbapi API.",
    image: "/images/5.png",
    tags: ["React"],
    source: "https://github.com/Leviantt/movie-search/",
    visit: "https://leviantt.github.io/movie-search/",
    id: 4,
  },
  {
    title: "Store",
    description: "Page in an online store with a shopping cart.",
    image: "/images/6.png",
    tags: ["React", "Typescript", "React-router-dom"],
    source: "https://github.com/Leviantt/store/",
    visit: "https://comforting-melomakarona-6107b0.netlify.app/",
    id: 5,
  },
];
